/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GarcomRouteImport } from './routes/garcom'
import { Route as ChurrasqueiroRouteImport } from './routes/churrasqueiro'
import { Route as CaixaRouteImport } from './routes/caixa'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GarcomMesaMesaIdRouteImport } from './routes/garcom.mesa.$mesaId'

const GarcomRoute = GarcomRouteImport.update({
  id: '/garcom',
  path: '/garcom',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurrasqueiroRoute = ChurrasqueiroRouteImport.update({
  id: '/churrasqueiro',
  path: '/churrasqueiro',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaRoute = CaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GarcomMesaMesaIdRoute = GarcomMesaMesaIdRouteImport.update({
  id: '/mesa/$mesaId',
  path: '/mesa/$mesaId',
  getParentRoute: () => GarcomRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/caixa': typeof CaixaRoute
  '/churrasqueiro': typeof ChurrasqueiroRoute
  '/garcom': typeof GarcomRouteWithChildren
  '/garcom/mesa/$mesaId': typeof GarcomMesaMesaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/caixa': typeof CaixaRoute
  '/churrasqueiro': typeof ChurrasqueiroRoute
  '/garcom': typeof GarcomRouteWithChildren
  '/garcom/mesa/$mesaId': typeof GarcomMesaMesaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/caixa': typeof CaixaRoute
  '/churrasqueiro': typeof ChurrasqueiroRoute
  '/garcom': typeof GarcomRouteWithChildren
  '/garcom/mesa/$mesaId': typeof GarcomMesaMesaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/caixa'
    | '/churrasqueiro'
    | '/garcom'
    | '/garcom/mesa/$mesaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/caixa'
    | '/churrasqueiro'
    | '/garcom'
    | '/garcom/mesa/$mesaId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/caixa'
    | '/churrasqueiro'
    | '/garcom'
    | '/garcom/mesa/$mesaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CaixaRoute: typeof CaixaRoute
  ChurrasqueiroRoute: typeof ChurrasqueiroRoute
  GarcomRoute: typeof GarcomRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/garcom': {
      id: '/garcom'
      path: '/garcom'
      fullPath: '/garcom'
      preLoaderRoute: typeof GarcomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/churrasqueiro': {
      id: '/churrasqueiro'
      path: '/churrasqueiro'
      fullPath: '/churrasqueiro'
      preLoaderRoute: typeof ChurrasqueiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa': {
      id: '/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof CaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garcom/mesa/$mesaId': {
      id: '/garcom/mesa/$mesaId'
      path: '/mesa/$mesaId'
      fullPath: '/garcom/mesa/$mesaId'
      preLoaderRoute: typeof GarcomMesaMesaIdRouteImport
      parentRoute: typeof GarcomRoute
    }
  }
}

interface GarcomRouteChildren {
  GarcomMesaMesaIdRoute: typeof GarcomMesaMesaIdRoute
}

const GarcomRouteChildren: GarcomRouteChildren = {
  GarcomMesaMesaIdRoute: GarcomMesaMesaIdRoute,
}

const GarcomRouteWithChildren =
  GarcomRoute._addFileChildren(GarcomRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CaixaRoute: CaixaRoute,
  ChurrasqueiroRoute: ChurrasqueiroRoute,
  GarcomRoute: GarcomRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
